periods_block = {'class': 'detailMS'}
periods_headers = {'class': 'detailMS__headerText'}
period_row = {'class': 'detailMS__incidentRow'}
period_row_time = {'class': ['time-box', 'time-box-wide']}
period_row_y_card = {'class': 'y-card'}
period_row_substitution_name = {'class': ['substitution-in-name', 'substitution-out-name']}
period_row_participant_name = {'class': 'participant-name'}
period_row_soccer_ball = {'class': 'soccer-ball'}
period_row_sub_incident_name = {'class': 'subincident-name'}
